### PR TITLE
Set fixes and updates.

### PR DESCRIPTION
**Pull request by jgornick**

### CODE REVIEW

**Comment by BolivarShagnasty** [comment]
@jgornick I appreciate you cleaning up several years worth of sloppiness :smile:

**Comment by jgornick** [comment]
Ha! No worries. I'm actually finding the issues when converting to JSON then into a database. (https://github.com/jgornick/swlcg-json)

**Comment by BolivarShagnasty** [comment]
Huh, is the database currently in use somewhere, or is it something for personal use?

**Comment by jgornick** [comment]
Currently, personal use. But providing an API and front-end whenever @bmb330 and I have time to finish it :) 

The end goal is to have a database that is maintained by the community (with an editorial workflow) and then we would provide OCTGN set XML. This would be nice for OCTGN maintainers, like you, so you don't have to maintain the sets database via XML files.

For reference: 
* https://github.com/jgornick/swlcg-api
* https://github.com/jgornick/swlcg

**Pull request merged**
